/**
 * Builds per-package vendor chunks for the canvas compiler.
 * Each chunk is a minified IIFE that assigns package exports to
 * globalThis.__CANVAS_VENDOR__[specifier].
 *
 * Run: bun run build:canvas-vendor
 */
import * as esbuild from 'esbuild'
import * as fs from 'node:fs'
import * as path from 'node:path'

const VENDOR_DIR = path.resolve(__dirname, '../lib/canvas/compiler/vendor')

type VendorChunkDef = {
  /** Output file name (without .generated.ts) */
  name: string
  /** Exported constant name */
  exportName: string
  /** Package specifiers to include */
  specifiers: string[]
  /**
   * Specifiers to shim to globalThis.__CANVAS_VENDOR__ (for add-on
   * chunks that depend on react-core without re-bundling it).
   */
  shimExternals?: string[]
  /** Additional global assignments (e.g., __CANVAS_REACT__ = React) */
  globalAliases?: Record<string, string>
}

const VENDOR_CHUNKS: VendorChunkDef[] = [
  {
    name: 'react-core',
    exportName: 'REACT_CORE_VENDOR_JS',
    specifiers: ['react', 'react-dom', 'react-dom/client', 'react/jsx-runtime'],
    globalAliases: {
      __CANVAS_REACT__: 'react',
      __CANVAS_REACT_DOM__: 'react-dom/client'
    }
  },
  {
    name: 'lucide-react',
    exportName: 'LUCIDE_REACT_VENDOR_JS',
    specifiers: ['lucide-react'],
    shimExternals: ['react', 'react/jsx-runtime']
  },
  {
    name: 'recharts',
    exportName: 'RECHARTS_VENDOR_JS',
    specifiers: ['recharts'],
    shimExternals: [
      'react',
      'react-dom',
      'react-dom/client',
      'react/jsx-runtime'
    ]
  },
  {
    name: 'motion-react',
    exportName: 'MOTION_REACT_VENDOR_JS',
    specifiers: ['motion/react'],
    shimExternals: ['react', 'react/jsx-runtime']
  },
  {
    name: 'date-fns',
    exportName: 'DATE_FNS_VENDOR_JS',
    specifiers: ['date-fns']
  }
]

function buildVendorEntry(def: VendorChunkDef): string {
  const lines: string[] = [
    'globalThis.__CANVAS_VENDOR__ = globalThis.__CANVAS_VENDOR__ || {};'
  ]
  for (const spec of def.specifiers) {
    const safe = spec.replace(/[^a-zA-Z0-9]/g, '_')
    lines.push(`import * as _${safe} from '${spec}';`)
    lines.push(
      `globalThis.__CANVAS_VENDOR__[${JSON.stringify(spec)}] = _${safe};`
    )
  }
  if (def.globalAliases) {
    for (const [globalName, specifier] of Object.entries(def.globalAliases)) {
      lines.push(
        `globalThis.${globalName} = globalThis.__CANVAS_VENDOR__[${JSON.stringify(specifier)}];`
      )
    }
  }
  return lines.join('\n')
}

/**
 * Creates an esbuild plugin that shims specified packages to read from
 * globalThis.__CANVAS_VENDOR__ instead of bundling them. This prevents
 * add-on chunks from re-bundling React.
 */
function createShimPlugin(externals: string[]): esbuild.Plugin {
  const externalSet = new Set(externals)
  return {
    name: 'vendor-shim-externals',
    setup(build) {
      build.onResolve({ filter: /.*/ }, args => {
        if (externalSet.has(args.path)) {
          return { path: args.path, namespace: 'vendor-shim' }
        }
      })
      build.onLoad({ filter: /.*/, namespace: 'vendor-shim' }, args => ({
        contents: `module.exports = globalThis.__CANVAS_VENDOR__[${JSON.stringify(args.path)}]`,
        loader: 'js'
      }))
    }
  }
}

async function buildChunk(def: VendorChunkDef): Promise<void> {
  const entry = buildVendorEntry(def)
  const plugins: esbuild.Plugin[] = []

  if (def.shimExternals?.length) {
    plugins.push(createShimPlugin(def.shimExternals))
  }

  const result = await esbuild.build({
    stdin: {
      contents: entry,
      loader: 'tsx',
      resolveDir: process.cwd()
    },
    bundle: true,
    write: false,
    format: 'iife',
    minify: true,
    platform: 'browser',
    target: ['es2020'],
    jsx: 'automatic',
    jsxImportSource: 'react',
    logLevel: 'silent',
    plugins
  })

  const js = result.outputFiles[0].text
  const sizeKB = (js.length / 1024).toFixed(0)

  const tsContent = [
    '// AUTO-GENERATED by scripts/build-canvas-vendor.ts',
    '// Do not edit manually. Regenerate with: bun run build:canvas-vendor',
    '',
    `export const ${def.exportName} = ${JSON.stringify(js)}`,
    ''
  ].join('\n')

  const outPath = path.join(VENDOR_DIR, `${def.name}.generated.ts`)
  fs.writeFileSync(outPath, tsContent, 'utf-8')
  console.log(
    `  ${def.name}: ${sizeKB} KB → ${path.relative(process.cwd(), outPath)}`
  )
}

async function main() {
  fs.mkdirSync(VENDOR_DIR, { recursive: true })

  console.log('Building canvas vendor chunks...')
  for (const def of VENDOR_CHUNKS) {
    await buildChunk(def)
  }
  console.log('Done.')
}

main().catch(err => {
  console.error('Failed to build canvas vendor chunks:', err)
  process.exit(1)
})
